[[redirects]]
  from = "/success"
  to = "/"
  status = 302

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true
  
[[redirects]]
  from = "/.netlify/functions/submission-created"
  to = "/.netlify/functions/submission-created"
  status = 200
  force = true
